/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ldsystem.*;
import ldventas.Ventas;
import ldInventario.Inventario;

/**
 *
 * @author luise
 */
public class VMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public VMenu() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContenedor = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnAlumnos = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        visor = new javax.swing.JPanel();
        btnApagar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnContenedor.setBackground(new java.awt.Color(144, 214, 255));

        pnMenu.setBackground(new java.awt.Color(56, 182, 255));
        pnMenu.setForeground(new java.awt.Color(56, 182, 255));

        btnInicio.setBackground(new java.awt.Color(56, 182, 255));
        btnInicio.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnAlumnos.setBackground(new java.awt.Color(56, 182, 255));
        btnAlumnos.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAlumnos.setText("Alumnas");
        btnAlumnos.setBorder(null);
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });

        btnVenta.setBackground(new java.awt.Color(56, 182, 255));
        btnVenta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnVenta.setText("Ventas");
        btnVenta.setBorder(null);
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        btnLista.setBackground(new java.awt.Color(56, 182, 255));
        btnLista.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnLista.setText("Lista");
        btnLista.setBorder(null);
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        btnInventario.setBackground(new java.awt.Color(56, 182, 255));
        btnInventario.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setBorder(null);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        visor.setBackground(new java.awt.Color(144, 214, 255));
        visor.setOpaque(false);
        visor.setLayout(new java.awt.BorderLayout());

        btnApagar.setBackground(new java.awt.Color(144, 214, 255));
        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apagado.png"))); // NOI18N
        btnApagar.setBorder(null);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnContenedorLayout = new javax.swing.GroupLayout(pnContenedor);
        pnContenedor.setLayout(pnContenedorLayout);
        pnContenedorLayout.setHorizontalGroup(
            pnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContenedorLayout.createSequentialGroup()
                .addGroup(pnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnContenedorLayout.createSequentialGroup()
                        .addGap(1050, 1050, 1050)
                        .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnContenedorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnContenedorLayout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(logo))
                            .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnContenedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnContenedorLayout.setVerticalGroup(
            pnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContenedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(pnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnContenedorLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(pnContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        int op
                = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres cerrar el programa?", "CONFIRMACION",
                        JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            System.exit(WIDTH);

            JOptionPane.showMessageDialog(null, "Hasta luego");

        } else {

            JOptionPane.showMessageDialog(null, "No se cerrara el programa");

        }//cierre del else
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        logo.setIcon(null); //Borra el logo

        //Manda a llamar el JPanel de AsistenciaDocente
        Inventario in1 = new Inventario();
        in1.setSize(1040, 440);
        in1.setLocation(0, 0);

        visor.removeAll();
        visor.add(in1, BorderLayout.CENTER);
        visor.revalidate();
        visor.repaint();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        logo.setIcon(null); //Borra el logo

        //Manda a llamar el JPanel de AsistenciaDocente
        AsistenciaDocente ad1 = new AsistenciaDocente();
        ad1.setSize(1040, 440);
        ad1.setLocation(0, 0);

        visor.removeAll();
        visor.add(ad1, BorderLayout.CENTER);
        visor.revalidate();
        visor.repaint();
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        logo.setIcon(null); //Borra el logo

        //Manda a llamar el JPanel de Ventas
        Ventas ven1 = new Ventas();
        ven1.setSize(1040, 440);
        ven1.setLocation(0, 0);

        visor.removeAll();
        visor.add(ven1, BorderLayout.CENTER);
        visor.revalidate();
        visor.repaint();
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed

        try {
            logo.setIcon(null); //Borra el logo
            
            //Manda a llamar el JPanel de NivelAlumna
            NivelAlumna nAl1 = new NivelAlumna();
            nAl1.setSize(1040, 440);
            nAl1.setLocation(0, 0);
            
            visor.removeAll();
            visor.add(nAl1, BorderLayout.CENTER);
            visor.revalidate();
            visor.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(VMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        logo.setIcon(null); //Borra el logo
        //Manda a llamar el JPanel de Menu2
        Menu2 m1 = new Menu2();
        m1.setSize(1040, 440);
        m1.setLocation(0, 0);

        visor.removeAll();
        visor.add(m1, BorderLayout.CENTER);
        visor.revalidate();
        visor.repaint();
    }//GEN-LAST:event_btnInicioActionPerformed

//    public static void main(String[] args) {
//
//        new VMenu().setVisible(true);
//
//    } // close main


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JToggleButton btnApagar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel pnContenedor;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel visor;
    // End of variables declaration//GEN-END:variables
}
