/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ayudas;

import ldsystem.*;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luise
 */
public class NivelAyuda extends javax.swing.JPanel {

    /**
     * Creates new form InscripcionNivelUno
     */
    public NivelAyuda() {
        initComponents();
        
        JOptionPane.showMessageDialog(null, "En esta parte muestran los nombres");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnIns = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlumnas = new javax.swing.JTable();
        tbAgregarAlumna = new javax.swing.JButton();
        tbnEliminarAlumna = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnIns.setBackground(new java.awt.Color(144, 214, 255));

        tbAlumnas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbAlumnas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datos de alumnas"
            }
        ));
        jScrollPane1.setViewportView(tbAlumnas);

        tbAgregarAlumna.setBackground(new java.awt.Color(85, 142, 213));
        tbAgregarAlumna.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbAgregarAlumna.setText("Agregar");
        tbAgregarAlumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAgregarAlumnaActionPerformed(evt);
            }
        });

        tbnEliminarAlumna.setBackground(new java.awt.Color(85, 142, 213));
        tbnEliminarAlumna.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbnEliminarAlumna.setText("Eliminar");
        tbnEliminarAlumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnEliminarAlumnaActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Si selecciona el boton de agregar podra agregar una nueva alumna");

        jLabel2.setText("y si desea borrar una alumna tendra que seleccionarla y precionar borrar");

        javax.swing.GroupLayout pnInsLayout = new javax.swing.GroupLayout(pnIns);
        pnIns.setLayout(pnInsLayout);
        pnInsLayout.setHorizontalGroup(
            pnInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnInsLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnRegresar)
                .addGap(141, 141, 141)
                .addGroup(pnInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addComponent(tbAgregarAlumna, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(tbnEliminarAlumna, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnInsLayout.setVerticalGroup(
            pnInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(pnInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInsLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnRegresar))
                    .addGroup(pnInsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2))
                    .addComponent(tbAgregarAlumna, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnEliminarAlumna, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(pnIns, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbAgregarAlumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAgregarAlumnaActionPerformed

    }//GEN-LAST:event_tbAgregarAlumnaActionPerformed

    private void tbnEliminarAlumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnEliminarAlumnaActionPerformed
        int op
                = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres eliminar esta alumna?", "CONFIRMACION",
                        JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            

            JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente");

        } else {

            JOptionPane.showMessageDialog(null, "No se ha eliminado ningun dato");

        }//cierre del else
    }//GEN-LAST:event_tbnEliminarAlumnaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        try {
            //Manda a llamar el JPanel de InscripcionNivelUno
            NivelAlumna nAl1 = new NivelAlumna();
            nAl1.setSize(1040, 440);
            nAl1.setLocation(0, 0);
            
            pnIns.removeAll();
            pnIns.add(nAl1, BorderLayout.CENTER);
            pnIns.revalidate();
            pnIns.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(NivelAyuda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnIns;
    private javax.swing.JButton tbAgregarAlumna;
    private javax.swing.JTable tbAlumnas;
    private javax.swing.JButton tbnEliminarAlumna;
    // End of variables declaration//GEN-END:variables
}
