/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ldsystem;

import Controlador.bd.SQLNombres;
import Controlador.bd.Transacciones;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import ldsystem.*;

/**
 *
 * @author luise
 */
public class Niveldos extends javax.swing.JPanel {
    
    Transacciones transacciones;
    DefaultTableModel modelo;
    public int idSeleccionado;   
    int indice = -1;

    /**
     * Creates new form Niveldos
     */
    public Niveldos() {
        initComponents();
        this.transacciones = new Transacciones();
        this.modelo = new DefaultTableModel();
        this.mostrarAlumnas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnInsdos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlumnas = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btAyuda1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnInsdos.setBackground(new java.awt.Color(144, 214, 255));

        tbAlumnas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        tbAlumnas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAlumnasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAlumnas);

        btnEliminar.setBackground(new java.awt.Color(85, 142, 213));
        btnEliminar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");

        btnAgregar.setBackground(new java.awt.Color(85, 142, 213));
        btnAgregar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");

        btAyuda1.setBackground(new java.awt.Color(85, 142, 213));
        btAyuda1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btAyuda1.setText("Ayuda");

        javax.swing.GroupLayout pnInsdosLayout = new javax.swing.GroupLayout(pnInsdos);
        pnInsdos.setLayout(pnInsdosLayout);
        pnInsdosLayout.setHorizontalGroup(
            pnInsdosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInsdosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInsdosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btAyuda1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pnInsdosLayout.setVerticalGroup(
            pnInsdosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInsdosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInsdosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAyuda1))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(pnInsdos, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbAlumnasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlumnasMouseClicked
        indice = tbAlumnas.getSelectedRow();
    }//GEN-LAST:event_tbAlumnasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAyuda1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnInsdos;
    private javax.swing.JTable tbAlumnas;
    // End of variables declaration//GEN-END:variables

    public void mostrarAlumnas(){
  
     this.modelo = new DefaultTableModel(){
         @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer que todas las celdas sean no editables
     }
     };
        this.modelo.addColumn("ID");
        this.modelo.addColumn("Nombres");
        this.modelo.addColumn("Apellidos");
        this.modelo.addColumn("Direccion");
        this.modelo.addColumn("Contacto");
        this.modelo.addColumn("ID Nivel");
     
     
     try {
            
            

            ResultSet resultado = this.transacciones.seleccionar(SQLNombres.verNombre2());

            while (resultado.next()) {
                Object [] alum = {
                resultado.getInt(1),
                resultado.getString(2),
                resultado.getString(3),
                resultado.getString(4),
                resultado.getString(5),
                resultado.getInt(6)
                

                };
                modelo.addRow(alum);
            }//cierra while
            this.tbAlumnas.setModel(modelo);
        } catch (Exception e) {
            System.out.println("error: " + e.getMessage());

        }//cierra catch
 }
}
        
